// <auto-generated />
using System;
using HotelManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313073428_InitialCreateee")]
    partial class InitialCreateee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelManagementSystem.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckinDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2026, 3, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckinDate = new DateTime(2026, 3, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckoutDate = new DateTime(2026, 3, 17, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            RoomId = 1,
                            Status = 2,
                            TotalPrice = 100m
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2026, 3, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckinDate = new DateTime(2026, 3, 18, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckoutDate = new DateTime(2026, 3, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            RoomId = 3,
                            Status = 1,
                            TotalPrice = 300m
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, City",
                            Email = "john@example.com",
                            Name = "John Doe",
                            PhoneNumber = "1234567890",
                            RegisteredDate = new DateTime(2026, 3, 13, 15, 34, 26, 775, DateTimeKind.Local).AddTicks(1798)
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave, Town",
                            Email = "jane@example.com",
                            Name = "Jane Smith",
                            PhoneNumber = "9876543210",
                            RegisteredDate = new DateTime(2026, 3, 13, 15, 34, 26, 776, DateTimeKind.Local).AddTicks(2134)
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Rd, Village",
                            Email = "mike@example.com",
                            Name = "Mike Johnson",
                            PhoneNumber = "5555555555",
                            RegisteredDate = new DateTime(2026, 3, 13, 15, 34, 26, 776, DateTimeKind.Local).AddTicks(2147)
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Elm St, City",
                            Email = "ginting@example.com",
                            Name = "Ginting Michael",
                            PhoneNumber = "5551234567",
                            RegisteredDate = new DateTime(2026, 3, 13, 15, 34, 26, 776, DateTimeKind.Local).AddTicks(2149)
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            PricePerNight = 50m,
                            RoomNumber = "101",
                            RoomType = 1
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            PricePerNight = 80m,
                            RoomNumber = "102",
                            RoomType = 2
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = false,
                            PricePerNight = 150m,
                            RoomNumber = "103",
                            RoomType = 3
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true,
                            PricePerNight = 50m,
                            RoomNumber = "201",
                            RoomType = 1
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = false,
                            PricePerNight = 80m,
                            RoomNumber = "202",
                            RoomType = 2
                        });
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Booking", b =>
                {
                    b.HasOne("HotelManagementSystem.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelManagementSystem.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HotelManagementSystem.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
